permalink: /:year/:month/:day/:title

safe: true
lsi: false
highlighter: pygments
markdown: redcarpet

title: Chris Yunker
email: chrisyunker@gmail.com
description: # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.yunker.io"
twitter_username: cyunker
github_username: chrisyunker

analytics:
  google_id: UA-58148811-6

comments:
  disqus_id: chrisyunkerblog

production_url: http://chrisyunker.github.io

exclude: ["vendor"]

gems:
- jekyll-mentions
- jemoji
- jekyll-redirect-from
- jekyll-sitemap

