title: Chris Yunker
email: chrisyunker@gmail.com
description:
baseurl: ""
url: "http://www.yunker.io"
date_format: "%Y %b %-d"
header_pages:
 - about.md

twitter_username: cyunker
github_username: chrisyunker
linkedin_username: chrisyunker

google_analytics: UA-58148811-6

comments: true
disqus_shortname: chrisyunkerblog

# Optional features
animated: false
show_related_posts: false
show_post_footers: false
show_social_icons: true
ajaxify_contact_form: false
enable_mathjax: false
extended_fonts: false
enable_anchorjs: false
# Preview image for social media aka og:image and twitter:image
post_preview_image: false

text:
  pagination:
    newer: 'Newer'
    older: 'Older'
  post:
    minute_read: 'minute read'
  og_locale: 'en_US'

markdown: kramdown
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink: pretty
paginate: 4
sass:
  style: compressed
plugins:
  - jekyll-paginate
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
