permalink: /:year/:month/:day/:title 

safe: true
lsi: false
highlighter: pygments
markdown: redcarpet

theme: simple

title: Chris Yunker
author:
  name: Chris Yunker
  email: chrisyunker@gmail.com
  github: chrisyunker
  twitter: cyunker

analytics:
  google_id: UA-28316611-1

comments:
  disqus_id: chrisyunkerblog

production_url: http://chrisyunker.github.io

exclude: ["vendor"]

stylus:
  compress: true
  path: ./style

gems:
- jekyll-mentions
- jemoji
- jekyll-redirect-from
- jekyll-sitemap

