permalink: /:year/:month/:day/:title 

safe: true
lsi: false
pygments: true
markdown: rdiscount

theme : simple

title : Chris Yunker
author :
  name : Chris Yunker
  email : chris@yunker.io
  github : chrisyunker
  twitter : cyunker

analytics :
  google_id : UA-28316611-2

comments :
  disqus_id : chrisyunkerblog

production_url : http://yunker.io

